### PR TITLE
feat: Show filename when importing with PartSeg in napari

### PR DESCRIPTION
**Pull request by daviddaytw**
Hi,

Thank you for developing this fantastic tool! It has been incredibly valuable for our research.

While working with PartSeg in Napari, we noticed that the filename does not appear in the layer names, making distinguishing between multiple imported files challenging. To address this, I’ve updated the code in this pull request to add the filename as a prefix to the layer names.

I’m open to feedback on this approach and would love your thoughts or suggestions for further improvement!

Best,
David

## Summary by Sourcery

New Features:
- Add filename as a prefix to layer names when importing with PartSeg in Napari.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new method for adjusting color values, enhancing color processing capabilities.
	- Added conditional functionality for adding color based on the version of the application.
	- Improved layer naming conventions by incorporating file name prefixes for better clarity.
	- Added a new property for selecting layer naming formats in settings.
	- Introduced a new enumeration for layer naming formats with multiple options.
	- Added new test cases to validate layer naming format functionality.

- **Bug Fixes**
	- Enhanced handling of alpha channels in color strings to ensure accurate color representation.

### CODE REVIEW

**Comment by Czaki** [comment]
Hm. Could you describe more the use case? 

My biggest worry is that the name could be a little too long and be unreadable in napari interface. 
As you mae see on this screenshot, when I check out your PR and run:
Screenshot 2024-12-07 at 01 20 08

The file name consumes almost all place, and details of channel names are not visible. 

The name of the file for the current active layer is visible on the status bar:

Screenshot 2024-12-07 at 01 23 26

It is also visible as tooltip:

Screenshot 2024-12-07 at 01 24 06

But both things require mouse interaction. 

Maybe some clipping of file name could be a solution? But it will be easier to decide if you provide some description of the use case. 

Te PR will also require updating the test that checks if layer name is expected.

**Comment by daviddaytw** [comment]
Hi @Czaki,

Thank you for sharing your feedback on this PR!

I agree that the filename could become overly long. Do you have any suggestions on how we might truncate or simplify it effectively? If you think the channel name is the priority, maybe we can use a format like `Ch1-T1 | stack1_component2.tif`?

Regarding the use case, we need to load multiple stains simultaneously (e.g., ASYM32, POLYGA, NeuN) in Napari for analysis. Specifically, we used PartSeg's ROI Analysis Extraction tool for thresholding. The places you mentioned show the filename, but in the selection box within the tool panel, we must select based on the layer name. In the current workflow, we need to rename the layer every time we load a file, or else we will be confused when doing the analysis.

Please let me know what files I should update about the test. I'm happy to do it!

Looking forward to your thoughts! 

Best regards,
David

**Comment by Czaki** [comment]
Hard question. I even started thinking about allowing configuring this by settings...

If it is mainly for layer combo box, I prefer the `channel name | file name` format. 

But If you think, that making this configurable is a good idea, we may go this direction.

**Comment by Czaki** [comment]
@daviddaytw I have created #1228. Once I merge it (1 or 2 days), there will be ready skeleton for this change.

**Comment by daviddaytw** [comment]
Sounds good, I am looking forward to it!

**Comment by daviddaytw** [comment]
Hi @Czaki 

Thank you for adding the Settings Editor! This is going to be very helpful for PartSeg users.
I currently have limited bandwidth on this, but I will look into it as soon as possible!

Best,
David

**Comment by daviddaytw** [comment]
Hi @Czaki ,

I added a section to the Setting Editor according to your instructions.

Best,
David

**Comment by Czaki** [comment]
@daviddaytw Will it be possible for you to add tests for this code, or should I push to your branch?

**Comment by daviddaytw** [comment]
> @daviddaytw Will it be possible for you to add tests for this code, or should I push to your branch?

@Czaki Can you push to my branch if that's easy for you?

**Comment by daviddaytw** [comment]
That's awesome tests, thanks!

**Comment by Czaki** [comment]
I will cut a new release in a few following days.

**Comment by Czaki** [comment]
@daviddaytw PartSeg 0.16.0 uploaded to pypi. 
In a few days will be on conda-forge too.

**Pull request merged**
